/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Native_One */

#ifndef _Included_Native_One
#define _Included_Native_One
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Native_One
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Native_One_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
